import = ["/home/diego/.config/alacritty/themes/themes/github_light.toml"]

[font]
size = 13.0

[font.normal]
family = "JetBrains Mono"
style = "Medium"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "Return"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Alt"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Alt"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "J"
mods = "Alt|Shift"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "K"
mods = "Alt|Shift"

[[keyboard.bindings]]
action = "ResetFontSize"
key = "R"
mods = "Alt|Shift"

[selection]
save_to_clipboard = true

[window]
decorations_theme_variant = "Light"
dynamic_title = true
