[general]
import = ["/home/diego/.config/alacritty/themes/themes/github_light.toml"]

[font]
size = 12

[font.normal]
# see ~/.config/fontconfig/conf.d/10-emoji.conf
family = "terminal-font"

# style = "ExtraLight"
# family = "Source Code Pro"
# style = "Regular"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "Return"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Alt"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Alt"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "J"
mods = "Alt|Shift"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "K"
mods = "Alt|Shift"

[[keyboard.bindings]]
action = "ResetFontSize"
key = "R"
mods = "Alt|Shift"

[[keyboard.bindings]]
action = "ToggleViMode"
key = "D"
mods = "Alt"

[selection]
save_to_clipboard = true

[window]
decorations_theme_variant = "Light"
dynamic_title = true

# Spread additional padding evenly around the terminal content.
dynamic_padding = true
